CREATE TABLE uteexpress.shipments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE REFERENCES uteexpress.orders(id),
    provider_id BIGINT NOT NULL REFERENCES uteexpress.shipping_providers(id),
    assigned_shipper_id BIGINT NOT NULL REFERENCES uteexpress.users(id),
    status VARCHAR(32) NOT NULL,
    shipping_service_snapshot VARCHAR(32) NOT NULL,
    fee_snapshot NUMERIC(19,2) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 2,
    failure_reason TEXT,
    picked_up_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_shipments_status CHECK (status IN ('ASSIGNED', 'PICKED_UP', 'SHIPPING', 'DELIVERY_FAILED', 'DELIVERED', 'RETURNED_TO_SENDER', 'CANCELLED')),
    CONSTRAINT ck_shipments_service CHECK (shipping_service_snapshot ~ '^[A-Z][A-Z0-9_]{0,31}$'),
    CONSTRAINT ck_shipments_fee CHECK (fee_snapshot >= 0 AND fee_snapshot <> 'NaN'::numeric),
    CONSTRAINT ck_shipments_attempts CHECK (attempt_count BETWEEN 0 AND max_attempts AND max_attempts = 2),
    CONSTRAINT ck_shipments_version CHECK (version >= 0)
);
CREATE INDEX ix_shipments_assigned_shipper_status ON uteexpress.shipments(assigned_shipper_id, status);

CREATE TABLE uteexpress.shipment_assignment_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT NOT NULL REFERENCES uteexpress.shipments(id),
    previous_shipper_id BIGINT REFERENCES uteexpress.users(id),
    assigned_shipper_id BIGINT NOT NULL REFERENCES uteexpress.users(id),
    actor_id BIGINT NOT NULL REFERENCES uteexpress.users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_shipment_assignment_changed CHECK
        (previous_shipper_id IS NULL OR previous_shipper_id <> assigned_shipper_id)
);
CREATE INDEX ix_shipment_assignment_history_shipment ON uteexpress.shipment_assignment_history(shipment_id, id);
