CREATE TABLE uteexpress.shipping_providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(32) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_shipping_provider_code CHECK (code ~ '^[A-Z][A-Z0-9_]{0,31}$'),
    CONSTRAINT ck_shipping_provider_name CHECK (btrim(name) <> '' AND name = btrim(name)),
    CONSTRAINT ck_shipping_provider_version CHECK (version >= 0)
);

CREATE TABLE uteexpress.shipping_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL REFERENCES uteexpress.shipping_providers(id),
    service_code VARCHAR(32) NOT NULL,
    destination_region VARCHAR(20) NOT NULL,
    fee NUMERIC(19,2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_shipping_rates_route UNIQUE (provider_id, service_code, destination_region),
    CONSTRAINT ck_shipping_rate_service CHECK (service_code ~ '^[A-Z][A-Z0-9_]{0,31}$'),
    CONSTRAINT ck_shipping_rate_region CHECK (destination_region ~ '^[A-Z0-9][A-Z0-9_-]{0,19}$'),
    CONSTRAINT ck_shipping_rate_fee CHECK (fee >= 0 AND fee = trunc(fee)),
    CONSTRAINT ck_shipping_rate_version CHECK (version >= 0)
);
