CREATE TABLE uteexpress.carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_carts PRIMARY KEY (id),
    CONSTRAINT fk_carts_user_id FOREIGN KEY (user_id) REFERENCES uteexpress.users (id),
    CONSTRAINT uq_carts_user_id UNIQUE (user_id),
    CONSTRAINT ck_carts_version_nonnegative CHECK (version >= 0)
);

CREATE TABLE uteexpress.cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cart_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    selected BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_cart_items PRIMARY KEY (id),
    CONSTRAINT fk_cart_items_cart_id FOREIGN KEY (cart_id) REFERENCES uteexpress.carts (id),
    CONSTRAINT fk_cart_items_product_id FOREIGN KEY (product_id) REFERENCES uteexpress.products (id),
    CONSTRAINT uq_cart_items_cart_id_product_id UNIQUE (cart_id, product_id),
    CONSTRAINT ck_cart_items_quantity_positive CHECK (quantity > 0)
);

CREATE INDEX ix_cart_items_product_id ON uteexpress.cart_items (product_id);
