CREATE TABLE uteexpress.addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    receiver_name VARCHAR(120) NOT NULL,
    phone VARCHAR(32) NOT NULL,
    province_code VARCHAR(64) NOT NULL,
    district VARCHAR(120) NOT NULL,
    detail VARCHAR(255) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_addresses PRIMARY KEY (id),
    CONSTRAINT fk_addresses_user_id FOREIGN KEY (user_id)
        REFERENCES uteexpress.users (id),
    CONSTRAINT ck_addresses_receiver_name_not_blank CHECK (btrim(receiver_name) <> ''),
    CONSTRAINT ck_addresses_phone_not_blank CHECK (btrim(phone) <> ''),
    CONSTRAINT ck_addresses_province_code_not_blank CHECK (btrim(province_code) <> ''),
    CONSTRAINT ck_addresses_district_not_blank CHECK (btrim(district) <> ''),
    CONSTRAINT ck_addresses_detail_not_blank CHECK (btrim(detail) <> ''),
    CONSTRAINT ck_addresses_version_nonnegative CHECK (version >= 0)
);

CREATE INDEX ix_addresses_user_id ON uteexpress.addresses (user_id, id);
CREATE UNIQUE INDEX uq_addresses_user_id_default
    ON uteexpress.addresses (user_id)
    WHERE is_default = TRUE;
