CREATE TABLE uteexpress.shops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    owner_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(120) NOT NULL,
    logo_key VARCHAR(512),
    banner_key VARCHAR(512),
    description VARCHAR(2000),
    pickup_address VARCHAR(500) NOT NULL,
    status VARCHAR(32) NOT NULL,
    rejection_reason VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_shops PRIMARY KEY (id),
    CONSTRAINT fk_shops_owner_id FOREIGN KEY (owner_id)
        REFERENCES uteexpress.users (id),
    CONSTRAINT uq_shops_owner_id UNIQUE (owner_id),
    CONSTRAINT uq_shops_slug UNIQUE (slug),
    CONSTRAINT ck_shops_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_shops_slug_canonical CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    CONSTRAINT ck_shops_pickup_address_not_blank CHECK (btrim(pickup_address) <> ''),
    CONSTRAINT ck_shops_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_shops_rejection_reason CHECK (
        (status = 'REJECTED' AND rejection_reason IS NOT NULL AND btrim(rejection_reason) <> '')
        OR (status <> 'REJECTED' AND rejection_reason IS NULL)
    ),
    CONSTRAINT ck_shops_version_nonnegative CHECK (version >= 0)
);

CREATE INDEX ix_shops_status_created_at ON uteexpress.shops (status, created_at, id);
