-- Requires AUTH-01 users migration; never omit the actor FK to bypass ordering.
CREATE TABLE uteexpress.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    actor_id BIGINT,
    action VARCHAR(64) NOT NULL,
    target_type VARCHAR(64) NOT NULL,
    target_id BIGINT NOT NULL,
    before_summary VARCHAR(1000) NOT NULL,
    after_summary VARCHAR(1000) NOT NULL,
    reason VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id),
    CONSTRAINT fk_audit_logs_actor_id FOREIGN KEY (actor_id) REFERENCES uteexpress.users (id),
    CONSTRAINT ck_audit_logs_actor_id CHECK (actor_id IS NULL OR actor_id > 0),
    CONSTRAINT ck_audit_logs_target_id CHECK (target_id > 0),
    CONSTRAINT ck_audit_logs_action CHECK (action ~ '^[A-Z][A-Z0-9_]{0,63}$'),
    CONSTRAINT ck_audit_logs_target_type CHECK (target_type ~ '^[A-Z][A-Z0-9_]{0,63}$'),
    CONSTRAINT ck_audit_logs_reason CHECK (reason ~ '^[A-Z][A-Z0-9_]{0,63}$')
);
CREATE INDEX ix_audit_logs_actor_created_at ON uteexpress.audit_logs (actor_id, created_at DESC, id DESC);
CREATE INDEX ix_audit_logs_target_created_at ON uteexpress.audit_logs (target_type, target_id, created_at DESC, id DESC);
CREATE INDEX ix_audit_logs_created_at ON uteexpress.audit_logs (created_at DESC, id DESC);
COMMENT ON TABLE uteexpress.audit_logs IS 'Append-only governance history; no credentials or personal payloads';
