CREATE TABLE uteexpress.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(254) NOT NULL,
    normalized_email VARCHAR(254) NOT NULL,
    username VARCHAR(30) NOT NULL,
    normalized_username VARCHAR(30) NOT NULL,
    password_hash VARCHAR(60) NOT NULL,
    status VARCHAR(32) NOT NULL,
    email_verified_at TIMESTAMPTZ,
    token_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_normalized_email UNIQUE (normalized_email),
    CONSTRAINT uq_users_normalized_username UNIQUE (normalized_username),
    CONSTRAINT ck_users_email_not_blank CHECK (btrim(email) <> ''),
    CONSTRAINT ck_users_normalized_email_not_blank CHECK (btrim(normalized_email) <> ''),
    CONSTRAINT ck_users_username_format CHECK (username ~ '^[A-Za-z0-9._-]{3,30}$'),
    CONSTRAINT ck_users_normalized_username_format CHECK (normalized_username ~ '^[a-z0-9._-]{3,30}$'),
    CONSTRAINT ck_users_status CHECK (status IN ('PENDING_VERIFICATION', 'ACTIVE', 'LOCKED', 'DISABLED')),
    CONSTRAINT ck_users_token_version_nonnegative CHECK (token_version >= 0),
    CONSTRAINT ck_users_version_nonnegative CHECK (version >= 0)
);

CREATE TABLE uteexpress.roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_roles PRIMARY KEY (id),
    CONSTRAINT uq_roles_code UNIQUE (code),
    CONSTRAINT ck_roles_code CHECK (code IN ('USER', 'VENDOR', 'MANAGER', 'ADMIN', 'SHIPPER'))
);

CREATE TABLE uteexpress.user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user_id FOREIGN KEY (user_id) REFERENCES uteexpress.users (id),
    CONSTRAINT fk_user_roles_role_id FOREIGN KEY (role_id) REFERENCES uteexpress.roles (id)
);

INSERT INTO uteexpress.roles (code)
VALUES ('USER'), ('VENDOR'), ('MANAGER'), ('ADMIN'), ('SHIPPER');
