CREATE TABLE uteexpress.commission_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rate_percent NUMERIC(7,4) NOT NULL,
    effective_from TIMESTAMPTZ NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT NOT NULL REFERENCES uteexpress.users (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_commission_policies_effective_from UNIQUE (effective_from),
    CONSTRAINT ck_commission_policies_rate CHECK (rate_percent >= 0 AND rate_percent <= 100)
);

CREATE INDEX ix_commission_policies_effective
    ON uteexpress.commission_policies (effective_from DESC);

ALTER TABLE uteexpress.orders
    ADD CONSTRAINT fk_orders_commission_policy_id
    FOREIGN KEY (commission_policy_id) REFERENCES uteexpress.commission_policies (id);
