-- Fail if the migration role cannot install/use btree_gist; never substitute a race-prone guard.
CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA uteexpress;

CREATE TABLE uteexpress.promotions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    discount_percent NUMERIC NOT NULL,
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    active BOOLEAN NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_promotions PRIMARY KEY (id),
    CONSTRAINT fk_promotions_product_id FOREIGN KEY (product_id) REFERENCES uteexpress.products(id),
    CONSTRAINT fk_promotions_created_by FOREIGN KEY (created_by) REFERENCES uteexpress.users(id),
    CONSTRAINT ck_promotions_parent_ids CHECK (product_id > 0 AND created_by > 0),
    CONSTRAINT ck_promotions_name CHECK (btrim(name) <> '' AND name = btrim(name)),
    CONSTRAINT ck_promotions_discount_percent CHECK (discount_percent > 0 AND discount_percent <= 100),
    CONSTRAINT ck_promotions_window CHECK (isfinite(starts_at) AND isfinite(ends_at) AND starts_at < ends_at),
    CONSTRAINT ck_promotions_version CHECK (version >= 0),
    CONSTRAINT ex_promotions_product_window EXCLUDE USING gist (
        product_id WITH =, tstzrange(starts_at, ends_at, '[)') WITH &&
    ) WHERE (active)
);
CREATE INDEX ix_promotions_product_id ON uteexpress.promotions(product_id, id);

-- Explicit as-of time, shared across filtering, sorting, counts and projected prices.
-- Numeric ROUND on nonnegative values is whole-dong HALF_UP, matching common.money.Money.
CREATE FUNCTION uteexpress.product_prices_at(pricing_at TIMESTAMPTZ)
RETURNS TABLE (product_id BIGINT, base_price NUMERIC, discount NUMERIC, effective_price NUMERIC)
LANGUAGE SQL STABLE AS $$
    SELECT p.id, p.price,
           round(p.price * COALESCE(pr.discount_percent, 0) / 100, 0),
           p.price - round(p.price * COALESCE(pr.discount_percent, 0) / 100, 0)
      FROM uteexpress.products p
      LEFT JOIN uteexpress.promotions pr ON pr.product_id = p.id
       AND pr.active AND pr.starts_at <= pricing_at AND pricing_at < pr.ends_at
$$;
