CREATE TABLE uteexpress.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    shop_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(4000),
    price NUMERIC(19,2) NOT NULL,
    stock INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT fk_products_shop_id FOREIGN KEY (shop_id)
        REFERENCES uteexpress.shops (id),
    CONSTRAINT fk_products_category_id FOREIGN KEY (category_id)
        REFERENCES uteexpress.categories (id),
    CONSTRAINT ck_products_parent_ids CHECK (shop_id > 0 AND category_id > 0),
    CONSTRAINT ck_products_name_not_blank CHECK (btrim(name) <> '' AND name = btrim(name)),
    CONSTRAINT ck_products_price CHECK (
        price > 0 AND price <> 'NaN'::numeric AND price = trunc(price)
    ),
    CONSTRAINT ck_products_stock_nonnegative CHECK (stock >= 0),
    CONSTRAINT ck_products_status CHECK (status IN ('ACTIVE', 'HIDDEN')),
    CONSTRAINT ck_products_version_nonnegative CHECK (version >= 0)
);

CREATE INDEX ix_products_category_id_status
    ON uteexpress.products (category_id, status);
CREATE INDEX ix_products_shop_id_status
    ON uteexpress.products (shop_id, status);

CREATE TABLE uteexpress.product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    storage_key VARCHAR(512) NOT NULL,
    position INTEGER NOT NULL,
    alt_text VARCHAR(255),
    CONSTRAINT pk_product_images PRIMARY KEY (id),
    CONSTRAINT fk_product_images_product_id FOREIGN KEY (product_id)
        REFERENCES uteexpress.products (id),
    CONSTRAINT uq_product_images_product_id_position UNIQUE (product_id, position),
    CONSTRAINT ck_product_images_product_id_positive CHECK (product_id > 0),
    CONSTRAINT ck_product_images_storage_key_not_blank CHECK (btrim(storage_key) <> ''),
    CONSTRAINT ck_product_images_position_nonnegative CHECK (position >= 0)
);
