-- TD ORD-01: approved phased-FK migration. Add exactly the three deferred
-- constraints in later migrations after HP shops/products and QD policies merge.
CREATE TABLE uteexpress.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_code VARCHAR(255) NOT NULL,
    checkout_key VARCHAR(255) NOT NULL,
    request_hash VARCHAR(255) NOT NULL,
    buyer_id BIGINT NOT NULL,
    shop_id BIGINT NOT NULL,
    status VARCHAR(255) NOT NULL,
    receiver_name VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    province_code VARCHAR(255) NOT NULL,
    district VARCHAR(255) NOT NULL,
    detail VARCHAR(255) NOT NULL,
    subtotal NUMERIC(19,2) NOT NULL,
    discount_total NUMERIC(19,2) NOT NULL,
    shipping_fee NUMERIC(19,2) NOT NULL,
    grand_total NUMERIC(19,2) NOT NULL,
    commission_amount NUMERIC(19,2) NOT NULL,
    commission_policy_id BIGINT,
    commission_rate_snapshot NUMERIC NOT NULL,
    ready_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    inventory_released_at TIMESTAMPTZ,
    cancellation_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT uq_orders_order_code UNIQUE (order_code),
    CONSTRAINT uq_orders_buyer_id_checkout_key UNIQUE (buyer_id, checkout_key),
    CONSTRAINT fk_orders_buyer_id FOREIGN KEY (buyer_id) REFERENCES uteexpress.users (id),
    -- Deferred: fk_orders_shop_id -> uteexpress.shops(id) (HP).
    -- Deferred: fk_orders_commission_policy_id -> uteexpress.commission_policies(id) (QD).
    CONSTRAINT ck_orders_status CHECK (status IN ('NEW', 'CONFIRMED', 'PICKED_UP', 'SHIPPING', 'DELIVERED', 'CANCELLED', 'RETURN_REQUESTED', 'RETURNED', 'REFUNDED')),
    CONSTRAINT ck_orders_identity CHECK (btrim(order_code) <> '' AND btrim(checkout_key) <> '' AND btrim(request_hash) <> ''),
    CONSTRAINT ck_orders_address CHECK (btrim(receiver_name) <> '' AND btrim(phone) <> '' AND btrim(province_code) <> '' AND btrim(district) <> '' AND btrim(detail) <> ''),
    CONSTRAINT ck_orders_parent_ids CHECK (buyer_id > 0 AND shop_id > 0 AND (commission_policy_id IS NULL OR commission_policy_id > 0)),
    CONSTRAINT ck_orders_money CHECK (subtotal >= 0 AND subtotal <> 'NaN'::numeric AND discount_total >= 0 AND discount_total <= subtotal AND shipping_fee >= 0 AND shipping_fee <> 'NaN'::numeric AND grand_total >= 0 AND grand_total = subtotal - discount_total + shipping_fee),
    CONSTRAINT ck_orders_commission CHECK (commission_rate_snapshot BETWEEN 0 AND 100 AND commission_amount >= 0 AND commission_amount <= subtotal - discount_total),
    CONSTRAINT ck_orders_version_nonnegative CHECK (version >= 0)
);
CREATE INDEX ix_orders_buyer_id_created_at ON uteexpress.orders (buyer_id, created_at);
CREATE INDEX ix_orders_shop_id_status ON uteexpress.orders (shop_id, status);

CREATE TABLE uteexpress.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name_snapshot VARCHAR(255) NOT NULL,
    unit_price NUMERIC(19,2) NOT NULL,
    discount_snapshot NUMERIC(19,2) NOT NULL,
    final_unit_price NUMERIC(19,2) NOT NULL,
    quantity INTEGER NOT NULL,
    line_total NUMERIC(19,2) NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (id),
    CONSTRAINT fk_order_items_order_id FOREIGN KEY (order_id) REFERENCES uteexpress.orders (id),
    -- Deferred: fk_order_items_product_id -> uteexpress.products(id) (HP).
    CONSTRAINT ck_order_items_product CHECK (product_id > 0 AND btrim(product_name_snapshot) <> ''),
    CONSTRAINT ck_order_items_quantity CHECK (quantity > 0),
    CONSTRAINT ck_order_items_money CHECK (unit_price > 0 AND unit_price <> 'NaN'::numeric AND discount_snapshot >= 0 AND discount_snapshot <= unit_price AND final_unit_price = unit_price - discount_snapshot AND line_total = final_unit_price * quantity)
);
CREATE INDEX ix_order_items_order_id ON uteexpress.order_items (order_id);

CREATE TABLE uteexpress.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    method VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    amount NUMERIC(19,2) NOT NULL,
    provider_reference VARCHAR(255),
    attempt_key VARCHAR(255) NOT NULL,
    paid_at TIMESTAMPTZ,
    expired_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_payments PRIMARY KEY (id),
    CONSTRAINT fk_payments_order_id FOREIGN KEY (order_id) REFERENCES uteexpress.orders (id),
    CONSTRAINT uq_payments_attempt_key UNIQUE (attempt_key),
    CONSTRAINT uq_payments_provider_reference UNIQUE (provider_reference),
    CONSTRAINT ck_payments_method CHECK (method IN ('COD', 'ONLINE')),
    CONSTRAINT ck_payments_status CHECK (status IN ('UNPAID', 'PAID')),
    CONSTRAINT ck_payments_amount CHECK (amount >= 0 AND amount <> 'NaN'::numeric),
    CONSTRAINT ck_payments_attempt_key CHECK (btrim(attempt_key) <> '')
);
CREATE INDEX ix_payments_order_id ON uteexpress.payments (order_id);
CREATE UNIQUE INDEX uq_payments_order_id_paid ON uteexpress.payments (order_id) WHERE status = 'PAID';

CREATE TABLE uteexpress.order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    from_status VARCHAR(255),
    to_status VARCHAR(255) NOT NULL,
    reason TEXT,
    actor_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_order_status_history PRIMARY KEY (id),
    CONSTRAINT fk_order_status_history_order_id FOREIGN KEY (order_id) REFERENCES uteexpress.orders (id),
    CONSTRAINT fk_order_status_history_actor_id FOREIGN KEY (actor_id) REFERENCES uteexpress.users (id),
    CONSTRAINT ck_order_status_history_from_status CHECK (from_status IN ('NEW', 'CONFIRMED', 'PICKED_UP', 'SHIPPING', 'DELIVERED', 'CANCELLED', 'RETURN_REQUESTED', 'RETURNED', 'REFUNDED')),
    CONSTRAINT ck_order_status_history_to_status CHECK (to_status IN ('NEW', 'CONFIRMED', 'PICKED_UP', 'SHIPPING', 'DELIVERED', 'CANCELLED', 'RETURN_REQUESTED', 'RETURNED', 'REFUNDED'))
);
CREATE INDEX ix_order_status_history_order_id_created_at ON uteexpress.order_status_history (order_id, created_at);
