-- PROMO-01. Prerequisites users/shops/orders already exist. Never backfill legacy orders/usages.
CREATE TABLE vouchers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    scope VARCHAR(16) NOT NULL,
    type VARCHAR(16) NOT NULL,
    shop_id BIGINT,
    value NUMERIC NOT NULL,
    max_discount NUMERIC(19,2),
    min_subtotal NUMERIC(19,2) NOT NULL,
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    total_limit BIGINT NOT NULL,
    per_user_limit BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_vouchers_code UNIQUE (code),
    CONSTRAINT fk_vouchers_shop_id FOREIGN KEY (shop_id) REFERENCES shops(id),
    CONSTRAINT fk_vouchers_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT ck_vouchers_code CHECK (code ~ '^[A-Z0-9][A-Z0-9_-]{0,63}$'),
    CONSTRAINT ck_vouchers_scope CHECK (
        (scope = 'SHOP' AND shop_id IS NOT NULL) OR (scope = 'PLATFORM' AND shop_id IS NULL)),
    CONSTRAINT ck_vouchers_value CHECK (value > 0 AND value <> 'NaN'::numeric AND
        ((type = 'PERCENTAGE' AND value <= 100) OR
         (type = 'FIXED' AND value = trunc(value) AND value <= 99999999999999999))),
    CONSTRAINT ck_vouchers_money CHECK (
        min_subtotal >= 0 AND min_subtotal <> 'NaN'::numeric AND min_subtotal = trunc(min_subtotal) AND
        (max_discount IS NULL OR (max_discount >= 0 AND max_discount <> 'NaN'::numeric AND max_discount = trunc(max_discount)))),
    CONSTRAINT ck_vouchers_window CHECK (starts_at < ends_at),
    CONSTRAINT ck_vouchers_limits CHECK (total_limit > 0 AND per_user_limit > 0)
);
CREATE INDEX ix_vouchers_shop_id ON vouchers(shop_id);

ALTER TABLE orders ADD COLUMN voucher_id BIGINT;
ALTER TABLE orders ADD COLUMN voucher_code VARCHAR(64);
ALTER TABLE orders ADD COLUMN voucher_scope VARCHAR(16);
-- voucher_id is an immutable logical identity, like shipping_provider_id; display uses the stored code/scope/discount_total.
ALTER TABLE orders ADD CONSTRAINT ck_orders_voucher_snapshot CHECK (
    (voucher_id IS NULL AND voucher_code IS NULL AND voucher_scope IS NULL) OR
    (voucher_id IS NOT NULL AND voucher_id > 0 AND voucher_code IS NOT NULL AND
     voucher_code ~ '^[A-Z0-9][A-Z0-9_-]{0,63}$' AND voucher_scope IS NOT NULL AND voucher_scope IN ('SHOP','PLATFORM')));
ALTER TABLE orders ADD CONSTRAINT uq_orders_id_buyer_id UNIQUE (id, buyer_id);

CREATE TABLE voucher_usages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL,
    discount_amount NUMERIC(19,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    released_at TIMESTAMPTZ,
    CONSTRAINT fk_voucher_usages_voucher_id FOREIGN KEY (voucher_id) REFERENCES vouchers(id),
    CONSTRAINT fk_voucher_usages_user_id FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_voucher_usages_order_id FOREIGN KEY (order_id, user_id) REFERENCES orders(id, buyer_id),
    CONSTRAINT uq_voucher_usages_order_id UNIQUE (order_id),
    CONSTRAINT ck_voucher_usages_status CHECK (status IN ('REDEEMED', 'RELEASED')),
    CONSTRAINT ck_voucher_usages_release CHECK (
        (status = 'REDEEMED' AND released_at IS NULL) OR
        (status = 'RELEASED' AND released_at IS NOT NULL)),
    CONSTRAINT ck_voucher_usages_discount CHECK (
        discount_amount >= 0 AND discount_amount <> 'NaN'::numeric AND discount_amount = trunc(discount_amount))
);
-- Both active quota counts use this prefix index. Placement/release writers lock vouchers first.
CREATE INDEX ix_voucher_usages_voucher_id_user_id ON voucher_usages(voucher_id, user_id);
