CREATE TABLE uteexpress.otp_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    purpose VARCHAR(32) NOT NULL,
    code_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    attempts INTEGER NOT NULL DEFAULT 0,
    sent_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_otp_tokens PRIMARY KEY (id),
    CONSTRAINT fk_otp_tokens_user_id FOREIGN KEY (user_id)
        REFERENCES uteexpress.users (id),
    CONSTRAINT ck_otp_tokens_purpose CHECK (purpose IN ('EMAIL_VERIFICATION')),
    CONSTRAINT ck_otp_tokens_code_hash CHECK (code_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_otp_tokens_attempts_nonnegative CHECK (attempts >= 0),
    CONSTRAINT ck_otp_tokens_expiry CHECK (expires_at > sent_at),
    CONSTRAINT ck_otp_tokens_consumed_at CHECK (consumed_at IS NULL OR consumed_at >= sent_at)
);

CREATE INDEX ix_otp_tokens_user_purpose_sent
    ON uteexpress.otp_tokens (user_id, purpose, sent_at DESC, id DESC);
