CREATE TABLE uteexpress.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL REFERENCES uteexpress.users (id),
    order_id BIGINT REFERENCES uteexpress.orders (id),
    type VARCHAR(64) NOT NULL,
    title VARCHAR(160) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    read_at TIMESTAMPTZ,
    dedup_key VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_notifications_type CHECK (length(trim(type)) > 0),
    CONSTRAINT ck_notifications_title CHECK (length(trim(title)) > 0),
    CONSTRAINT ck_notifications_message CHECK (length(trim(message)) > 0)
);

CREATE INDEX idx_notifications_recipient_read_created
    ON uteexpress.notifications (recipient_id, read_at, created_at DESC, id DESC);
